name: Update Version File

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate version.json
        run: |
          echo "{ \"commit\": \"${GITHUB_SHA::7}\" }" > version.json

      - name: Commit version file
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add version.json
          git diff --staged --quiet && exit 0

          git commit -m "Update version.json"
          git push